[2024-03-12T18:31:52.671+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Flow.snapshot manual__2024-03-12T18:05:45.652427+00:00 [queued]>
[2024-03-12T18:31:52.909+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Flow.snapshot manual__2024-03-12T18:05:45.652427+00:00 [queued]>
[2024-03-12T18:31:52.924+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-03-12T18:31:53.367+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): snapshot> on 2024-03-12 18:05:45.652427+00:00
[2024-03-12T18:31:53.471+0000] {standard_task_runner.py:60} INFO - Started process 416 to run task
[2024-03-12T18:31:53.692+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_Flow', 'snapshot', 'manual__2024-03-12T18:05:45.652427+00:00', '--job-id', '1028', '--raw', '--subdir', 'DAGS_FOLDER/etl2.py', '--cfg-path', '/tmp/tmpq2dko56b']
[2024-03-12T18:31:53.916+0000] {standard_task_runner.py:88} INFO - Job 1028: Subtask snapshot
[2024-03-12T18:32:06.382+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1028 for task snapshot ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 416)
[2024-03-12T18:32:07.496+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T18:32:07.694+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
