[2024-03-09T11:56:56.974+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Sales_ETL.truncate_mrr_stg manual__2024-03-09T11:56:38.365006+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
