[2024-05-02T18:58:55.425+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Flow.insert_data_from_files scheduled__2024-04-30T21:11:00+00:00 [queued]>
[2024-05-02T18:58:55.451+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Flow.insert_data_from_files scheduled__2024-04-30T21:11:00+00:00 [queued]>
[2024-05-02T18:58:55.453+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 9
[2024-05-02T18:58:55.496+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): insert_data_from_files> on 2024-04-30 21:11:00+00:00
[2024-05-02T18:58:55.508+0000] {standard_task_runner.py:60} INFO - Started process 3735 to run task
[2024-05-02T18:58:55.517+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_Flow', 'insert_data_from_files', 'scheduled__2024-04-30T21:11:00+00:00', '--job-id', '3224', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp16clw9og']
[2024-05-02T18:58:55.524+0000] {standard_task_runner.py:88} INFO - Job 3224: Subtask insert_data_from_files
[2024-05-02T18:58:55.663+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_Flow.insert_data_from_files scheduled__2024-04-30T21:11:00+00:00 [running]> on host 9100669c2df2
[2024-05-02T18:58:56.375+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='ETL_Flow' AIRFLOW_CTX_TASK_ID='insert_data_from_files' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T21:11:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T21:11:00+00:00'
[2024-05-02T18:58:57.134+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-02T18:58:57.402+0000] {sql.py:572} INFO - Done loading. Loaded a total of 50 rows into MRR_Dim_Customers
[2024-05-02T18:58:57.677+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-02T18:58:59.356+0000] {sql.py:572} INFO - Done loading. Loaded a total of 312 rows into MRR_Fact_Events
[2024-05-02T18:58:59.477+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-02T18:58:59.862+0000] {sql.py:572} INFO - Done loading. Loaded a total of 77 rows into MRR_Dim_Products
[2024-05-02T18:59:00.070+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-02T18:59:00.813+0000] {sql.py:572} INFO - Done loading. Loaded a total of 155 rows into MRR_Fact_Orders
[2024-05-02T18:59:00.938+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-02T18:59:02.298+0000] {sql.py:572} INFO - Done loading. Loaded a total of 261 rows into MRR_Fact_Details
[2024-05-02T18:59:02.299+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-02T18:59:02.343+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=ETL_Flow, task_id=insert_data_from_files, execution_date=20240430T211100, start_date=20240502T185855, end_date=20240502T185902
[2024-05-02T18:59:02.481+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-02T18:59:02.513+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-02T18:59:03.040+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
